### ISSUE TITLE
Cannot scroll over dragable content

### ISSUE THREAD

**Issue by elBotija** [drag-drop-touch-js/dragdroptouch#12]
I've been developing a dragable table for mobile devices. I found that this js does not work as expected in some devices(Ipod, Ipad, Iphone 5,6,6+, android < lollipop). The issue im having is that one cannot scroll the device over the content defined as dragable. 
To fix this issue i have added a small delay in the `_touchstart` function

**Comment by larssn** [comment]
Your 500ms delay causes dragging to feel quite weird now.

**Comment by dreadrocksean** [comment]
I agree.

**Comment by KeithGillette** [comment]
I found that the [`mobile-drag-drop`](https://github.com/timruffles/mobile-drag-drop) polyfill, when used with its optional `scroll-behavior` module, can be configured with a `holdToDrag` time delay to scrolling over dragable content.
