### ISSUE TITLE
In angularJs what is the syntax to import this into polyfills.ts?

### ISSUE THREAD

**Issue by hath74** [drag-drop-touch-js/dragdroptouch#20]
I've looked all over and can't find an answer to this. I'm using angular 5.

**Comment by Bernardo-Castilho** [comment]
Can't you just use a <script> element?

<script src='scripts/DragDropTouch.js"></script>

**Comment by pinnprophead** [comment]
With Angular CLI, I think dragdroptouch would have to be an NPM package. Bernardo, would you mind if I created an NPM package for it, or has it been done already?

Once the npm package has been created, then you would install the package, and reference it in polyfills.js

**Comment by Bernardo-Castilho** [comment]
I would not mind at all, that would actually be great!

Thank you for your help!

**Comment by pinnprophead** [comment]
It looks like it's already been published out there:

https://www.npmjs.com/package/drag-drop-touch-polyfill

**Comment by pinnprophead** [comment]
Also a newer one: 
https://www.npmjs.com/package/drag-drop-touch

**Comment by moniikag** [comment]
In Angular (not JS) you need to add it to `scripts`, inside `angular.json` file `architect > build > options`, e.g.:
```
"assets": [
            "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              "src/DragDropTouch.js"
            ]
```

**Comment by the-real-flo** [comment]
As it is a polyfill, I prefer to add it in polyfills.ts: `import 'drag-drop-touch';` after `npm install`ing, but I guess that's a matter of taste 😃

**Comment by Pomax** [comment]
I'm closing this because this isn't really an angular issue: just load the polyfill in your HTML. The "OG" web stack still applies.
