### ISSUE TITLE
Demo doesn't seem to work with Chrome devices panel

### ISSUE THREAD

**Issue by gaurav5430** [drag-drop-touch-js/dragdroptouch#27]
The demo doesn't work with Chrome devices panel, when switching to a mobile device.

Steps to reproduce: 
1. Load the page in Desktop mode.
2. Open developer tools.
3. toggle device to any mobile device.
4. The touch based drag and drop events do not work anymore.

I suspect this might be related to switching devices after the page is loaded, as on a new page reload with mobile device selected, it seems to work fine.

It also works fine on my mobile chrome.

Desktop Chrome version: 79

**Comment by Pomax** [comment]
I'm closing this as fixed, especially given that #77 got addressed.
