### ISSUE TITLE
Drag doesn't work when page is longer and needs to be scrolled.

### ISSUE THREAD

**Issue by ukw** [drag-drop-touch-js/dragdroptouch#3]
Hello,
First of all thanks for taking your time to publish this drag and drop.
I have a problem with it if the page has scroll (is bigger than the demo page) on iOS. (tested on iphone se)
Any idea how to fix this issue?
Also is it possible to scroll while dragging like on desktop?

Thanks,
ukw.

**Comment by carlosjeurissen** [comment]
I'm dealing with the same issue. @ukw were you able to resolve your issue or find another solution?

**Comment by ukw** [comment]
Unfortunately didn't had time to find a work around,

**Comment by dreadrocksean** [comment]
#metoo

**Comment by dreadrocksean** [comment]
Could be due to the passive listener errors I'm getting in Chrome.

**Comment by dreadrocksean** [comment]
Is there any way that the user could be given the option to {passive: false} ?

**Comment by KeithGillette** [comment]
I found that the [`mobile-drag-drop`](https://github.com/timruffles/mobile-drag-drop) polyfill supports scrolling while dragging, allowing one to drop a dragged element on a drop zone outside of the original scrolling viewport.

**Comment by Pomax** [comment]
I'm closing this issue mostly because a lot of the code has changed since this was originally filed, so if this is still a concern on the current version, please file a new issue and we can have a look at this.
