### ISSUE TITLE
Awesome polyfill! What about scrolling while dragging on Android Chrome browser

### ISSUE THREAD

**Issue by JSHound** [drag-drop-touch-js/dragdroptouch#35]
Is there an easy way to get it to scroll the page/div while dragging on Android Chrome?  My drop target may be down at the end of a long div that would require scrolling while dragging.

**Comment by nandita121189** [comment]
Hi @JSHound ,

Did you find any fix for this? Even I am struggling with the same issue.

**Comment by clamchoda** [comment]
@nandita121189 you could do that with [edge scrolling](https://stackoverflow.com/a/29038309/591285) pretty easily.

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed and how much the code has changed since this issue was filed: there is now an option to enable scrolling that hopefully addresses the original issue. If not, please file a new issue so we can look at it "afresh".
