### ISSUE TITLE
How to import this file in reactjs?

### ISSUE THREAD

**Issue by phongtran-uit** [drag-drop-touch-js/dragdroptouch#36]
i want to use this file in my reactjs app, how can i import and run it?

**Comment by Bernardo-Castilho** [comment]
You can add a script tag with the src parameter set to the location of the DragDropTouch.js file, e.g.

    <script src="DragDropTouch.js"></script>

**Comment by HDv2b** [comment]
I have `import "./polyfills/DragDropTouch";` in my App.js working well for me

**Comment by Pomax** [comment]
This library does not care about any particular framework: whether you're in React, Angular, Ember, Elixir, vanilla Js: it doesn't matter. Just load the polyfill in your page HTML (as in, the _actual_ HTML you're serving) as a script element and you're good to go.
