### ISSUE TITLE
Is it possible to make this a default behaviour on desktop as well?

### ISSUE THREAD

**Issue by salat-23** [drag-drop-touch-js/dragdroptouch#63]
By using this polyfill, the browser detects keypresses even when dragging (which is not a thing with a native html5 drag and drop). Is this possible to make this polyfill function in desktop browser?

**Comment by Pomax** [comment]
As of a few weeks ago: it is: if you're using the most recent version you can use the library will be enabled regardless of whether you're on a touch device or not, based on the `forceListen` option, which is set to `true` by default (but can of course be set to `false` if that's not what you want)
