### ISSUE TITLE
Should not start touch-dragging when source element has draggable="false"

### ISSUE THREAD

**Issue by Bernardo-Castilho** [drag-drop-touch-js/dragdroptouch#74]
In the demo:

With the mouse, you can drag the panel that contains an image by dragging the image itself.

However, you cannot do that using touch. I believe that used to be possible (that's why the demo has a panel with an image in it).

**Comment by Pomax** [comment]
(and also make sure to add that as an explicit test)

**Comment by Bernardo-Castilho** [comment]
I suspect the problem is with the _closestDraggable method:

```
_closestDraggable(element: HTMLElement | null) {
    for (let e = element; e !== null; e = e.parentElement) {
      if (e.getAttribute(`draggable`) || e.draggable) {
        return e;
      }
    }
    return null;
  }

```

I suspect it should be 

```
_closestDraggable(element: HTMLElement | null) {
    for (let e = element; e !== null; e = e.parentElement) {
      if (e.getAttribute(`draggable`) === "true" || e.draggable) {
        return e;
      }
    }
    return null;
  }
```

But I haven't tested this...

**Comment by Pomax** [comment]
that would make sense, let's see what the HTML spec says about `draggable`.

**Comment by Pomax** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable claims:

> **Warning:** This attribute is [enumerated](https://developer.mozilla.org/en-US/docs/Glossary/Enumerated) and not Boolean. A value of true or false is mandatory, and shorthand like `<img draggable>` is forbidden. The correct usage is `<img draggable="false">`

so you're right, we have to check for the _actual_ value.

**Comment by Pomax** [comment]
Added that change, and created a third test case (yay, tests!) that confirms things now work as intended.

**Comment by Bernardo-Castilho** [comment]
Actually, the latest version of the original code was this:

```
_closestDraggable(element: HTMLElement | null) {
    for (let e = element; e !== null; e = e.parentElement) {
      if (e.draggable) {
        return e;
      }
    }
    return null;
  }
```
And it works as expected. The e.draggable property handles the whole thing, no need to even look at the attribute.

**Comment by Pomax** [comment]
hm, I don't remember why I even changed that, because yeah, that should already work just fine... let me restore it to that because more code in this case just means more bug surface. Good catch, thank you so you much!
