### ISSUE TITLE
add DEBUG to the source

### ISSUE THREAD

**Issue by Pomax** [drag-drop-touch-js/dragdroptouch#79]
Adding a `const DEBUG = true` with a nice amount of `if (DEBUG) console.log(...)` should make gaining insight into what the library is doing easier, and the esbuild treeshaking should mean that when set to `false`, all the unreachable code paths get stripped from the `dist` targets.

**Comment by Bernardo-Castilho** [comment]
Nice!

**Comment by Pomax** [comment]
Digging through the esbuilds docs a bit more, rather than "a const" it can use labelled statements and preserve/drop based on those, which is even nicer. https://esbuild.github.io/api/#drop-labels

**Comment by Bernardo-Castilho** [comment]
Cool! I thought only Svelte used labels ;-)

**Comment by Pomax** [comment]
Labels is one of those things that no one knows JS has had since the beginning of time but no one uses because if you _need_ them, you're probably trying to apply the lessons you learned in a different programming language to JS, and you're going to have a bad time.
